version: "3.7"
services:
  web:
    build: ../client
    ports:
      - 3000:3000
    volumes:
      - ../client/src/:/app
    links:
      - server
  server:
    build: .
    expose:
      - 80
    environment:
      API_HOST: ${API_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - .:/app
    command: python app.py
